### ISSUE TITLE
Fehler im Log

### ISSUE THREAD

**Issue by AlGu318** [ioBroker/ioBroker.pushsafer#11]
Hallo,

ich bekomme hin und wieder diese Fehlermeldungen im Log wenn eine Nachricht über JavaScript gesendet werden soll. Die Nachricht kommt auch an.

host.ioBroker-PI3 | 2017-08-30 22:31:14.706 | error | instance system.adapter.pushsafer.0 terminated with code 0 (OK)
-- | -- | -- | --
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at _combinedTickCallback (internal/process/next_tick.js:80:11)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at endReadableNT (_stream_readable.js:974:12)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at IncomingMessage.emit (events.js:185:7)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at emitNone (events.js:91:20)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at IncomingMessage. (/opt/iobroker/node_modules/iobroker.pushsafer/node_modules/pushsafer-notifications/lib/pushsafer.js:72:11)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at Pushsafer.errors (/opt/iobroker/node_modules/iobroker.pushsafer/node_modules/pushsafer-notifications/lib/pushsafer.js:25:11)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | at Object.parse (native)
pushsafer.0 | 2017-08-30 22:31:14.120 | error | SyntaxError: Unexpected end of JSON input
pushsafer.0 | 2017-08-30 22:31:14.108 | error | uncaught exception: Unexpected end of JSON input

Brauchst du mehr Infos? Node Version oder ähnliches?

Danke und Gruß AlGu

**Comment by LovelySunshine** [comment]
Should be fixed by this: https://github.com/appzer/nodeJS-pushsafer/pull/1
