### ISSUE TITLE
Update pushsafer

### ISSUE THREAD

**Issue by appzer** [ioBroker/ioBroker.pushsafer#15]
Hello,

can you update the pushsafer module!

**New sounds** 0-60
**New icons** 1-177

**New Parameter**

**pr** = Priority
-2 = lowest priority
-1 = lower priority
0 = normal priority
1 = high priority
2 = highest priority

**re** = Retry / resend
Integer 60-10800 (60s steps): Time in seconds, after a message shuld resend.

**ex** = Expire
Integer 60-10800: Time in seconds, after the retry/resend should stop.

**a** = Answer
1 = Answer is possible
0 = Answer is not possible.

Take a look at their API description:
[https://www.pushsafer.com/en/pushapi](https://www.pushsafer.com/en/pushapi)

**Comment by appzer** [comment]
any news

**Comment by GermanBluefox** [comment]
No news. It is one of 300 adapters.
