### ISSUE TITLE
warn: pushsafer.0 (62054) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!

### ISSUE THREAD

**Issue by Kaembo** [ioBroker/ioBroker.pushsafer#20]
Will the adapter stop working with the current js-controller 3.1.6?

**Comment by Apollon77** [comment]
No, this was moved at least to js.controller 3.2 (September 2020+)

**Comment by Kaembo** [comment]
Thanks for the reply. Actually the problem was solved (and the warning removed) by installing the Adapter version from github. I was using the one from NPM and that is a very old one... Not sure why this was never updated....
