### ISSUE TITLE
pushsafer Adapter

### ISSUE THREAD

**Issue by appzer** [ioBroker/ioBroker.pushsafer#4]
Hallo,

Einstellungen vom Pushsafer Adapter können nicht gespeichert werden.
Ich habe keine Ahnung warum. Hatte mich beim erstellen des Adapters an dem von Pushover angelehnt.

Grüße Kevin

**Comment by GermanBluefox** [comment]
Ich nehme an, du hast das Problem gefixt. oder?

**Comment by appzer** [comment]
ich denke es lag an der Variable token <> privatekey

aber ich bekomme jetzt einen Fehler bei der Installation des npm packages in iobroker

$ ./iobroker add pushsafer
npm install iobroker.pushsafer --production --prefix "C:/ioBroker" (System call)
host.SIML install adapter pushsafer
ERROR: host.SIML error: reading io-package.json SyntaxError: Unexpected string
ERROR: process exited with code 14

Grüße Kevin

**Comment by GermanBluefox** [comment]
Muss jetzt gehen
