### ISSUE TITLE
Pushsafer

### ISSUE THREAD

**Issue by appzer** [ioBroker/ioBroker.pushsafer#7]
Hallo,

über den Adapter Manager funktioniert die Installation noch nicht, nur über GIT da funktioniert alles tadellos (Installation und auch das Versenden).

Ich sieht so aus, als wäre im Manager nur die Version 0.1.0 und nicht die 0.1.3 installierbar.

pushsafer Adapter	This adapter allows to send pushsafer notifications from ioBroker	notification pushsafer message	
0.1.0
0.1.3	[1/1]

Grüße Kevin

**Comment by GermanBluefox** [comment]
Jetzt soll gehen

**Comment by appzer** [comment]
Daumen hoch, funktioniert! Schönen Abend noch
